{
 "title": "MLOps API Monitoring",
 "tags": [
  "fastapi",
  "mlops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (last 5m)",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Average Latency (seconds)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Request Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  }
 ]
}