apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - prometheus-grafana.yaml
  - dashboards.yaml

images:
  - name: ghcr.io/albin0903/mlops
    newTag: local-dev
