apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Albin0903/mlops.git
    targetRevision: main
    path: gitops/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
